name: Build macOS Universal DMG (unsigned, both arch)

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

env:
  APP_NAME: "MyApp"                       # 変更可: アプリ名
  ENTRYPOINT: "main.py"                   # 変更可: エントリポイント
  BUNDLE_ID: "com.example.myapp"          # 変更可: バンドルID
  ICON_PATH: "assets/app.icns"            # 任意: 無ければ自動スキップ

jobs:
  # 1) Intel (x86_64) 版ビルド
  build-intel:
    runs-on: macos-13   # Intel ランナー
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install -U pip pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build .app (PyInstaller)
        run: |
          if [ -f mac.spec ]; then
            pyinstaller --noconfirm mac.spec
          else
            ICON_ARG=""
            if [ -f "$ICON_PATH" ]; then ICON_ARG="--icon $ICON_PATH"; fi
            pyinstaller --windowed --noconfirm \
              --name "${APP_NAME}" \
              --osx-bundle-identifier "${BUNDLE_ID}" \
              $ICON_ARG \
              "${ENTRYPOINT}"
          fi
          ls -la dist

      - name: Rename artifact (Intel)
        run: |
          mv "dist/${APP_NAME}.app" "dist/${APP_NAME}-Intel.app"

      - uses: actions/upload-artifact@v4
        with:
          name: app-intel
          path: dist/${{ env.APP_NAME }}-Intel.app

  # 2) Apple Silicon (arm64) 版ビルド
  build-arm:
    runs-on: macos-14   # Apple Silicon ランナー
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install -U pip pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build .app (PyInstaller)
        run: |
          if [ -f mac.spec ]; then
            pyinstaller --noconfirm mac.spec
          else
            ICON_ARG=""
            if [ -f "$ICON_PATH" ]; then ICON_ARG="--icon $ICON_PATH"; fi
            pyinstaller --windowed --noconfirm \
              --name "${APP_NAME}" \
              --osx-bundle-identifier "${BUNDLE_ID}" \
              $ICON_ARG \
              "${ENTRYPOINT}"
          fi
          ls -la dist

      - name: Rename artifact (AppleSilicon)
        run: |
          mv "dist/${APP_NAME}.app" "dist/${APP_NAME}-AppleSilicon.app"

      - uses: actions/upload-artifact@v4
        with:
          name: app-arm
          path: dist/${{ env.APP_NAME }}-AppleSilicon.app

  # 3) 両 .app を1つの DMG に梱包
  package-universal-dmg:
    runs-on: macos-14
    needs: [build-intel, build-arm]
    steps:
      - uses: actions/checkout@v4

      - name: Download Intel app
        uses: actions/download-artifact@v4
        with:
          name: app-intel
          path: bundle

      - name: Download AppleSilicon app
        uses: actions/download-artifact@v4
        with:
          name: app-arm
          path: bundle

      # 念のため、bundle直下に集約（階層ズレ対策）
      - name: Normalize bundle layout
        env:
          APP_NAME: ${{ env.APP_NAME }}
        run: |
          set -euxo pipefail
          echo "=== Tree before normalize ==="
          find bundle -maxdepth 3 -print

          INTEL_SRC="$(find bundle -type d -name "${APP_NAME}-Intel.app" -print -quit || true)"
          if [ -z "${INTEL_SRC}" ]; then
            INTEL_SRC="$(find bundle -type d -name "${APP_NAME}.app" -print -quit || true)"
          fi
          if [ -z "${INTEL_SRC}" ]; then
            echo "Intel .app not found under bundle/"
            exit 1
          fi
          mv -f "${INTEL_SRC}" "bundle/${APP_NAME}-Intel.app"

          ARM_SRC="$(find bundle -type d -name "${APP_NAME}-AppleSilicon.app" -print -quit || true)"
          if [ -z "${ARM_SRC}" ]; then
            ARM_SRC="$(find bundle -type d -name "${APP_NAME}.app" -print -quit || true)"
          fi
          if [ -z "${ARM_SRC}" ]; then
            echo "AppleSilicon .app not found under bundle/"
            exit 1
          fi
          if [ "${ARM_SRC}" = "bundle/${APP_NAME}-Intel.app" ]; then
            echo "ARM app path conflicts with Intel app path"
            exit 1
          fi
          mv -f "${ARM_SRC}" "bundle/${APP_NAME}-AppleSilicon.app"

          echo "=== Tree after normalize ==="
          find bundle -maxdepth 2 -print

      - name: Prepare bundle contents
        env:
          APP_NAME: ${{ env.APP_NAME }}
        run: |
          set -euxo pipefail
          cd bundle

          # 起動ランチャー（機種自動判別）: 変数展開あり。$DIR/$ARCH は実行時に必要なので \ でエスケープ
          cat > "Start ${APP_NAME}.command" <<SH
          #!/bin/bash
          DIR="\$(cd "\$(dirname "\$0")" && pwd)"
          ARCH="\$(uname -m)"
          if [ "\$ARCH" = "arm64" ]; then
            open "\$DIR/${APP_NAME}-AppleSilicon.app"
          else
            open "\$DIR/${APP_NAME}-Intel.app"
          fi
          SH
          chmod +x "Start ${APP_NAME}.command"

          # README（Gatekeeper案内・権限など）
          cat > "README.txt" <<TXT
          【${APP_NAME} の起動方法（署名・公証なし配布）】

          1) ${APP_NAME}-Intel.app と ${APP_NAME}-AppleSilicon.app の両方を同梱。
             - Apple シリコン: AppleSilicon 版
             - Intel: Intel 版
             不明なら「Start ${APP_NAME}.command」を実行してください。

          2) 初回は Gatekeeper でブロックされる場合:
             - Finder で .app を右クリック→「開く」→「開く」
             - または 設定 > プライバシーとセキュリティ の「このまま開く」

          3) PyAutoGUI 等を使う場合、設定 > プライバシーとセキュリティ で
             アクセシビリティ / 画面収録の権限を付与してください。

          4) うまく起動しない場合（自己責任）:
             xattr -dr com.apple.quarantine "/Applications/${APP_NAME}-Intel.app"
             xattr -dr com.apple.quarantine "/Applications/${APP_NAME}-AppleSilicon.app"
          TXT
          cd ..

      - name: Install create-dmg
        run: |
          brew install create-dmg || true

      - name: Make Universal DMG
        env:
          APP_NAME: ${{ env.APP_NAME }}
        run: |
          set -euxo pipefail
          mkdir -p dist
          OUT="dist/${APP_NAME}-Universal.dmg"

          echo "== create-dmg version =="
          create-dmg --version || true
          create-dmg --help | head -n 20 || true

          # 既存DMGを削除（--overwriteを使わない）
          rm -f "$OUT"

          # 背景あり/なしで分岐して作成（create-dmg が失敗したら hdiutil にフォールバック）
          if [ -f "packaging/dmg-background.png" ]; then
            if ! create-dmg \
              --volname "${APP_NAME}" \
              --window-pos 200 120 --window-size 720 440 \
              --icon "${APP_NAME}-Intel.app" 140 170 \
              --icon "${APP_NAME}-AppleSilicon.app" 320 170 \
              --icon "Start ${APP_NAME}.command" 500 170 \
              --app-drop-link 600 170 \
              --background "packaging/dmg-background.png" \
              "$OUT" "bundle"
            then
              echo "create-dmg failed -> fallback to hdiutil (no layout)"
              hdiutil create -volname "${APP_NAME}" -srcfolder "bundle" -ov -format UDZO "$OUT"
            fi
          else
            if ! create-dmg \
              --volname "${APP_NAME}" \
              --window-pos 200 120 --window-size 720 440 \
              --icon "${APP_NAME}-Intel.app" 140 170 \
              --icon "${APP_NAME}-AppleSilicon.app" 320 170 \
              --icon "Start ${APP_NAME}.command" 500 170 \
              --app-drop-link 600 170 \
              "$OUT" "bundle"
            then
              echo "create-dmg failed -> fallback to hdiutil (no layout)"
              hdiutil create -volname "${APP_NAME}" -srcfolder "bundle" -ov -format UDZO "$OUT"
            fi
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-Universal-DMG
          path: dist/${{ env.APP_NAME }}-Universal.dmg
